# Generated by Django 4.1.3 on 2022-11-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name_author',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Автор'),
        ),
    ]
