# Generated by Django 4.1.3 on 2022-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_city',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
